---
title: "Bee Landscape Population Modeling Attempt"
output: html_notebook:
  df_print: paged
---
```{r Set wd and read in libraries}
#Set working directory
knitr::opts_knit$set(root.dir = "~/Documents/GitHub/spatial-pop-modeling-test/Lonsdorf_Code_R/")

#Load libraries
library(tidyverse)
library(raster)
library(terra)
library(signal)
```

```{r Read in data layers}
#CDL floral resources, nesting, and foraging 
reclass_floral <- read.csv("CA_bees_floral.csv") %>%
  na.omit()
reclass_nest <- read.csv("CA_bees_nesting.csv") %>%
  na.omit()
reclass_lifehist <- read.csv("CA_bees_forage.csv") %>%
  na.omit()
```

```{r Create parameters}
cell_size <- 30 #30x30 m cell size
spec_num <- nrow(reclass_lifehist) #7 species in guild table
t_step <- 1 #time step

#Create raster file path
#Rasters taken from https://croplandcros.scinet.usda.gov/
base <- "Tiff Files/cdl_Yolo_"
raster_path <- paste0(base, (t_step + 2012), ".TIF") #create raster path based on time step
```

```{r Create empty arrays}
curr_LC <- terra::rast(raster_path) #assign current time step raster
curr_LC <- terra::trim(curr_LC)
extent <- terra::ext(curr_LC)

nr <- nrow(curr_LC) #number of rows in raster file
nc <- ncol(curr_LC) #number of columns in raster file

#Empty arrays/matrices
  #Arrays with nr, nc, spec_num, and all time steps (20)
  queen_array <- max_queen_array <- disperse <- array(0, dim = c(nr, nc, spec_num, 20))
  
  #Arrays with nr, nc, and spec_num
  queen_array_fin <- pol_ls_score <- array(0, dim = c(nr, nc, spec_num)) 

  #Matrix with species and all time steps (20)
  spec_pop <- matrix(0, nrow = spec_num, ncol = 20) #total species population at each time step
```

```{r Initialize queens}
queen_seed <- array(0, dim = c(nr, nc, spec_num))
queen_seed[611:620, 809:818, ] <- array(runif(n = (10 * 10 * spec_num)), dim = c(10, 10, spec_num)) #generate random number (0-1) in 10x10 array in the center of raster file
queen_array[ , , , 1] <- ifelse(queen_seed > 0.8, 1, 0) #assign a queen to a cell in array if > 0.8 (20% of cells will receive a queen)
```

```{r For loop}
for (t in 1:20){
  #Pull new raster file after 10 years of initializing
  if (t > 10) {
    raster_path <- paste0(base, (t+2012-10), ".TIF") #assign new raster file based on time step
    curr_LC <- terra::rast(raster_path) #current land cover raster
    curr_LC <- terra::trim(curr_LC) #remove excess NA rows
    curr_LC <-  terra::crop(curr_LC, extent) #crop land cover to same extent
  }
  
  #How many pixels of each cover type
  LC_type <- terra::freq(curr_LC)[,-1] %>%
    rename(type = value, num_pix = count)
  
  #Per capita reproduction rate
  for (s in 1:spec_num) {
    #Maximum number of nests per cell and max queens produced per nest
    max_nest <- reclass_lifehist$Nests[s] #maximum number of nests within a cell
    max_rep <- reclass_lifehist$Rep[s] #maximum number of queens produced per nest
    
    #Foraging distance matrix
    forage_dist <- reclass_lifehist$Disp[s] #foraging distance for each species
    radius <- 2*round(forage_dist/cell_size) #foraging radius in cells, 2 * avg foraging distance ->  95%
    X <- outer(-radius:radius, rep(1, length(-radius:radius)), FUN = function(x, y) x)  # matrix with center at center of circle
    Y <- outer(rep(1, length(-radius:radius)), -radius:radius, FUN = function(x, y) y)  # matrix with center at center of circle

    dist_mat <- as.matrix(cell_size * sqrt(X^2 + Y^2)) #distance to center of circle 
    dist_mat_decay <- exp(-dist_mat/forage_dist) * (dist_mat <= 2 * forage_dist) #exp decay to transform square into circle
    eff_forage <- sum(dist_mat_decay) #sum of circle distance matrix
    filter <- dist_mat_decay/eff_forage #normalized distant matrix (sums to 1)
    
    #Initialize floral and nesting habitat
    HF <- terra::as.matrix(curr_LC, wide = T)
    HN <- terra::as.matrix(curr_LC, wide = T)
    
    #Reclass landcover for each cover type by species 
    tot_LC <- nrow(reclass_nest) #number of land cover values in biophys table 
    for (i in 1:tot_LC) {
      HF[HF == reclass_floral[i,1]] <- reclass_floral[i, s + 1]/100 #convert values to proportion of floral resource suitability
      HN[HN == reclass_nest[i,1]] <- reclass_nest[i, s + 1]/100 #convert values to proportion of nesting suitability
    }
    
    #Convert HF to raster for convolution
    HF_rast <- terra::rast(HF)
    forage <- terra::focal(HF_rast, filter) #convolution based on distance and available floral resources
    forage_mat <- terra::as.matrix(forage, wide = T)
    pol_ls_score[,,s] <- HN * forage_mat
    
    #Disperse queens
    if (t > 1) {
      max_queen_array[,,s,t] <- matrix(1, nrow = nr, ncol = nc) * max_nest * HN #Calculate maximum number of queens per cell given landscape conditions
      queen_array[,,s,t] <- pmin(disperse[,,s,t-1], max_queen_array[,,s,t]) #Takes the smallest value between the two arrays. The number of queens in a cell cannot exceed the maximum.
      
      rep_temp <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc) #Random numbers to create variation
      range <- max(rep_temp) - min(rep_temp) #range of random values
      standardized <- floor(max_rep * 2 * (rep_temp - min(rep_temp))/range) #standardize values
      rep <- queen_array[,,s,t] * (standardized * forage_mat) #generate reproduction using 
      rep_rast <- terra::rast(rep)
      disperse[,,s,t] <- terra::as.matrix(focal(rep_rast, filter), wide = T) #convolution of dispersal of new queens 
      
    } else {
      #Where t = 1 (initial conditions)
      rep_temp <- matrix(rnorm(nr*nc), nrow = nr, ncol = nc)
      range <- max(rep_temp) - min(rep_temp)
      standardized <- floor(max_rep * 2 * (rep_temp - min(rep_temp))/range)
      rep <- queen_array[,,s,t] * (standardized * forage_mat)
      rep_rast <- terra::rast(rep)
      disperse[,,s,t] <- terra::as.matrix(focal(rep_rast, filter), wide = T)
    }
    
    spec_pop[s,t] <- sum(queen_array[,,s,t], na.rm = T) #population size of each species at given time step
    
    if (t == 20){
      queen_array_fin[,,s] <- queen_array[,,s,t]
      par(mfrow = c(2,3))
      image(queen_array_fin[,,s], axes = F)
    }
  }
}
```

```{r Images}
#Images for each species' pollinator landscape score
par(mfrow = c(2,3)) #set image parameters 2 x 3 grid, one image for each species
for (s in 1:spec_num) {
  image(pol_ls_score[,,s], axes = F) 
}

#Images for each time step/species (manually assign species s and run loop)
par(mfrow = c(4,5)) #set image parameters 4 x 5 grid, one image for each time step
for (i in 1:20) {
  image(disperse[,,s,i], axes = F)
}
```

```{r testing}

```



